name: pr check
on: [pull_request]
permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: installing node@18
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 18.16.1
      - name: installing dependencies
        run: npm ci
      - name: linting
        run: npm run lint
      - name: formatting
        run: npm run format
      - name: build
        run: npm run build
      - name: unit test
        run: npm run test
      - name: prepare test e2e
        run: npm run start & sleep 10
      - name: test e2e
        run: npm run test:e2e-ci
