name: pr check
on: [pull_request]
permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: installing node@18
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 20.9.0
      - name: installing dependencies
        run: npm ci
      - name: linting
        run: npm run lint
      - name: formatting
        run: npm run format
      - name: build
        run: npm run build
      - name: unit test
        run: npm run test
      - name: prepare test e2e
        run: npm run start & sleep 10
      - name: test e2e
        run: npm run test:e2e-ci
