name: pr check
on: [pull_request]
permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: installing node@18
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20.9.0
      - name: installing dependencies
        run: npm ci
      - name: linting
        run: npm run lint
      - name: formatting
        run: npm run format
      - name: build
        run: npm run build
      - name: unit test
        run: npm run test
      - name: prepare test e2e
        run: npm run start & sleep 10
      - name: test e2e
        run: npm run test:e2e-ci
